version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=https://otodokelife.com
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped 